included:
  - Sources
  - Tests
excluded:
  - Tests/UBTests/stubs
  - Tests/UBTests/XCTestManifests.swift
  - Package.swift
  - Tests/LinuxMain.swift
identifier_name:
  excluded:
    - id
    - to
    - on
