included:
  - Sources
  - Tests
excluded:
  - Sources/UB/Protobuf/
  - Tests/UBTests/stubs
  - Tests/UBTests/XCTestManifests.swift
  - Package.swift
  - Tests/LinuxMain.swift
identifier_name:
  excluded:
    - id
    - to
    - on
disabled_rules:
    - trailing_comma
