os: osx
language: swift
osx_image: xcode10.3
xcode_project: UB.xcodeproj
xcode_scheme: UB.Package

before_install:
  - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
      fi
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs))/' || {
        echo "Only docs were updated, stopping build process."
        exit
      }
  - make xcode

script: make test

notifications:
  email: false
