os: osx
language: swift
osx_image: xcode10.1
xcode_project: UB.xcodeproj
xcode_scheme: UB.Package

matrix:
  fast_finish: true
  include:
    - stage: test
      script: make test
    - stage: lint
      script:
        - make xcode
        - make lint
  allow_failures:
    - stage: lint

notifications:
  email: false
