os: osx
language: swift
osx_image: xcode11.0
xcode_project: UB.xcodeproj
xcode_scheme: UB.Package

branches:
  only:
    - master

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.html)|^(LICENSE)|^(docs)'
      then
        echo "Only docs were updated, not running the CI."
        exit
      fi
  - make xcode

script: make test

notifications:
  email: false
